### ISSUE TITLE
Other Pre-trained Models than BART?

### ISSUE THREAD

**Issue by ujjwalgoel06** [acolas1/GAP_COLING2022#1]
Can this repo be implemented for other LLM's like T5, Alpeca ?  if you can give me a rough idea on what all changes have to be made to accomodate?

**Comment by zhengyaoyaoyao** [comment]
can you share the dataset eventNarrative?  only down .json in net .

**Comment by acolas1** [comment]
> Can this repo be implemented for other LLM's like T5, Alpeca ? if you can give me a rough idea on what all changes have to be made to accommodate?

Sorry for the late reply as I have not been actively monitoring this. However, this repo can certainly be implemented to other open-sourced LLMs by replacing such as T5 where the code for the model is available. The main changes would need to be made in the[ model file](https://github.com/acolas1/GAP_COLING2022/blob/main/modeling_gap.py) and [run file](https://github.com/acolas1/GAP_COLING2022/blob/main/run_gap.py). Specifically, changes need to be made where the Bart-based model is referenced and modified, e.g. see the differences between BartEncoder and GAPBartEncoder. Please let us know if you have any other questions. Thanks!

**Comment by acolas1** [comment]
> can you share the dataset eventNarrative? only down .json in net .

Hi, we used the same process [here](https://github.com/acolas1/EventNarrative/blob/main/preprocess/preprocess_baselines/invest_huggingface.py) to preprocess the EventNarrative `.json` files into `.source`  `.target` `target.tok` files. Hope this helps!
